In [1]:
import numpy as np
import pandas as pd

In [3]:
data=pd.read_csv("spam.csv")
data.head()

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [6]:
data.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [7]:
data["spam"]=data["Category"].apply(lambda x:1 if x=="spam" else 0)
data.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [8]:
X=data["Message"]
X.head()

0    Go until jurong point, crazy.. Available only ...
1                        Ok lar... Joking wif u oni...
2    Free entry in 2 a wkly comp to win FA Cup fina...
3    U dun say so early hor... U c already then say...
4    Nah I don't think he goes to usf, he lives aro...
Name: Message, dtype: object

In [9]:
y=data["spam"]
y.head()

0    0
1    0
2    1
3    0
4    0
Name: spam, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=2)

In [12]:
from sklearn.feature_extraction.text import CountVectorizer

In [13]:
v=CountVectorizer()

In [14]:
X_train_count=v.fit_transform(X_train.values)
X_train_count.toarray()[:12]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [15]:
from sklearn.naive_bayes import GaussianNB

In [16]:
GNB=GaussianNB()

In [19]:
GNB.fit(X_train_count.toarray(),y_train)

GaussianNB()

In [20]:
email=["hey,lets go to party tonight!!","limited Offer valid upto 2 days"]
email_count=v.transform(email)

In [22]:
GNB.predict(email_count.toarray())

array([0, 1], dtype=int64)

In [24]:
X_test_count=v.transform(X_test.values)
GNB.score(X_test_count.toarray(),y_test)

0.9075584556824361

In [29]:
from sklearn.naive_bayes import MultinomialNB

In [30]:
MNB=MultinomialNB()

In [32]:
MNB.fit(X_train_count,y_train)

MultinomialNB()

In [33]:
MNB.predict(email_count)

array([0, 1], dtype=int64)

In [36]:
MNB.score(X_test_count,y_test)

0.9766177270255574

In [37]:
from sklearn.naive_bayes import BernoulliNB

In [38]:
BNB=BernoulliNB()

In [39]:
BNB.fit(X_train_count,y_train)

BernoulliNB()

In [40]:
BNB.predict(email_count)

array([0, 0], dtype=int64)

In [41]:
BNB.score(X_test_count,y_test)

0.9695486677542142

In [42]:
from sklearn.pipeline import Pipeline

In [47]:
esf=Pipeline([('vetorizer',CountVectorizer()),('mnb',MultinomialNB())])

In [48]:
esf.fit(X_train,y_train)

Pipeline(steps=[('vetorizer', CountVectorizer()), ('mnb', MultinomialNB())])

In [50]:
esf.score(X_test,y_test)*100

97.66177270255574